export const INIT = 'App/INIT';
export const INIT_SUCCESS = 'App/INIT_SUCCESS';
export const INIT_FAILURE = 'App/INIT_FAILURE';
export const CLEAN_AFTER_SIGN_OUT = 'App/CLEAN_AFTER_SIGN_OUT';
export const NAVIGATION_UPDATE = 'App/NAVIGATION_UPDATE';
export const OPEN_INFORM_TOASTER = 'App/OPEN_INFORM_TOASTER';
export const CLOSE_INFORM_TOASTER = 'App/CLOSE_INFORM_TOASTER';

export default {
  INIT, INIT_SUCCESS, INIT_FAILURE,
  CLEAN_AFTER_SIGN_OUT, NAVIGATION_UPDATE,
  OPEN_INFORM_TOASTER, CLOSE_INFORM_TOASTER
};
