export const FETCH_LIST = 'Lots/FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'Lots/FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'Lots/FETCH_LIST_FAILURE';

export const FETCH_BIDS = 'Lots/FETCH_BIDS';
export const FETCH_BIDS_SUCCESS = 'Lots/FETCH_BIDS_SUCCESS';
export const FETCH_BIDS_FAILURE = 'Lots/FETCH_BIDS_FAILURE';

export const FETCH_ITEM = 'Lots/FETCH_ITEM';
export const FETCH_ITEM_SUCCESS = 'Lots/FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'Lots/FETCH_ITEM_FAILURE';

export const FETCH_CITIES = 'Lots/FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'Lots/FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'Lots/FETCH_CITIES_FAILURE';

export const FETCH_CATEGORIES = 'Lots/FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'Lots/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'Lots/FETCH_CATEGORIES_FAILURE';


export const CREATE_LOT = 'Lots/CREATE_LOT';
export const CREATE_LOT_SUCCESS = 'Lots/CREATE_LOT_SUCCESS';
export const CREATE_LOT_FAILURE = 'Lots/CREATE_LOT_FAILURE';

export const ACCEPT_BID = 'Lots/ACCEPT_BID';
export const ACCEPT_BID_SUCCESS = 'Lots/ACCEPT_BID_SUCCESS';
export const ACCEPT_BID_FAILURE = 'Lots/ACCEPT_BID_FAILURE';

export const ACCEPT_PARTNERSHIP = 'Lots/ACCEPT_PARTNERSHIP';
export const ACCEPT_PARTNERSHIP_SUCCESS = 'Lots/ACCEPT_PARTNERSHIP_SUCCESS';
export const ACCEPT_PARTNERSHIP_FAILURE = 'Lots/ACCEPT_PARTNERSHIP_FAILURE';

export const CREATE_REQUEST = 'Lots/CREATE_REQUEST';
export const CREATE_REQUEST_SUCCESS = 'Lots/CREATE_REQUEST_SUCCESS';
export const CREATE_REQUEST_FAILURE = 'Lots/CREATE_REQUEST_FAILURE';

export const REQUEST_PARTNERSHIP = 'Lots/REQUEST_PARTNERSHIP';
export const REQUEST_PARTNERSHIP_SUCCESS = 'Lots/REQUEST_PARTNERSHIP_SUCCESS';
export const REQUEST_PARTNERSHIP_FAILURE = 'Lots/REQUEST_PARTNERSHIP_FAILURE';

export const OPEN_LOTS = 'Lots/OPEN_LOTS';
export const OPEN_LOT = 'Lots/OPEN_LOT';
export const OPEN_CREATE_LOT = 'Lots/OPEN_CREATE_LOT';
export const FILTER_LIST = 'Lots/FILTER_LIST';
export const CHANGE_PAGE = 'Lots/CHANGE_PAGE';
export const CHANGE_DATE = 'Lots/CHANGE_DATE';


// noinspection JSUnusedGlobalSymbols
export default {
  FETCH_LIST, FETCH_LIST_SUCCESS, FETCH_LIST_FAILURE,
  FETCH_ITEM, FETCH_ITEM_SUCCESS, FETCH_ITEM_FAILURE,
  OPEN_LOTS, OPEN_LOT, OPEN_CREATE_LOT,
  CREATE_LOT, CREATE_LOT_FAILURE, CREATE_LOT_SUCCESS,
  CREATE_REQUEST, CREATE_REQUEST_FAILURE, CREATE_REQUEST_SUCCESS,
  FETCH_BIDS, FETCH_BIDS_FAILURE, FETCH_BIDS_SUCCESS,
  FETCH_CATEGORIES, FETCH_CATEGORIES_FAILURE, FETCH_CATEGORIES_SUCCESS,
  REQUEST_PARTNERSHIP, REQUEST_PARTNERSHIP_FAILURE, REQUEST_PARTNERSHIP_SUCCESS,
  ACCEPT_PARTNERSHIP, ACCEPT_PARTNERSHIP_FAILURE, ACCEPT_PARTNERSHIP_SUCCESS,
  ACCEPT_BID, ACCEPT_BID_FAILURE, ACCEPT_BID_SUCCESS,
  FETCH_CITIES, FETCH_CITIES_SUCCESS, FETCH_CITIES_FAILURE,
  CHANGE_PAGE, FILTER_LIST, CHANGE_DATE
};

