export const FETCH_LIST = 'Lots/FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'Lots/FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'Lots/FETCH_LIST_FAILURE';

export const CREATE_LOT = 'Lots/CREATE_LOT';
export const CREATE_LOT_SUCCESS = 'Lots/CREATE_LOT_SUCCESS';
export const CREATE_LOT_FAILURE = 'Lots/CREATE_LOT_FAILURE';

export const OPEN_LOTS = 'Lots/OPEN_LOTS';
export const OPEN_LOT = 'Lots/OPEN_LOT';
export const OPEN_CREATE_LOT = 'Lots/OPEN_CREATE_LOT';

// noinspection JSUnusedGlobalSymbols
export default {
  FETCH_LIST, FETCH_LIST_SUCCESS, FETCH_LIST_FAILURE,
  OPEN_LOTS, OPEN_LOT, OPEN_CREATE_LOT,
  CREATE_LOT, CREATE_LOT_FAILURE, CREATE_LOT_SUCCESS,
};

