export const SIGN_IN = 'User/SIGN_IN';
export const SIGN_IN_SUCCESS = 'User/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'User/SIGN_IN_FAILURE';

export const SIGN_OUT = 'User/SIGN_OUT';

export const SIGN_UP = 'User/SIGN_UP';
export const SIGN_UP_SUCCESS = 'User/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'User/SIGN_UP_FAILURE';

export const FETCH_PROFILE = 'User/FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS= 'User/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'User/FETCH_PROFILE_FAILURE';

export const FETCH_USER = 'User/FETCH_USER';
export const FETCH_USER_SUCCESS= 'User/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'User/FETCH_USER_FAILURE';

export const EDIT_PROFILE = 'User/EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS= 'User/EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'User/EDIT_PROFILE_FAILURE';

export const EDIT_PROFILE_POPUP = 'User/EDIT_POPUP_PROFILE';
export const EDIT_PROFILE_POPUP_SUCCESS= 'User/EDIT_PROFILE_POPUP_SUCCESS';
export const EDIT_PROFILE_POPUP_FAILURE = 'User/EDIT_PROFILE_POPUP_FAILURE';

export const OPEN_REGISTRATION = 'User/OPEN_REGISTRATION';
export const OPEN_PROFILE = 'User/OPEN_PROFILE';
export const OPEN_EDIT_PROFILE = 'User/OPEN_EDIT_PROFILE';
export const SHOW_MODAL = 'User/SHOW_MODAL';
export const HIDE_MODAL = 'User/HIDE_MODAL';
export const LOCAL_AUTH = 'User/LOCAL_AUTH';
export const SHOW_POPUP = 'User/SHOW_POPUP';
export const HIDE_POPUP = 'User/HIDE_POPUP';

export const FILE_UPLOAD = 'User/FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS = 'User/FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'User/FILE_UPLOAD_FAILURE';
export const FILE_UPLOAD_CLEAR = 'User/FILE_UPLOAD_CLEAR';
export const FILE_DELETE = 'User/FILE_DELETE';



// noinspection JSUnusedGlobalSymbols
export default {
  SIGN_IN, SIGN_IN_FAILURE, SIGN_IN_SUCCESS,
  SIGN_OUT,
  FETCH_PROFILE, FETCH_PROFILE_FAILURE, FETCH_PROFILE_SUCCESS,
  SIGN_UP, SIGN_UP_FAILURE, SIGN_UP_SUCCESS,
  OPEN_REGISTRATION, OPEN_PROFILE, SHOW_MODAL, HIDE_MODAL,
  LOCAL_AUTH,
  FILE_UPLOAD, FILE_UPLOAD_SUCCESS, FILE_UPLOAD_FAILURE, FILE_UPLOAD_CLEAR, FILE_DELETE,OPEN_EDIT_PROFILE,
  EDIT_PROFILE, EDIT_PROFILE_SUCCESS, EDIT_PROFILE_FAILURE,
  FETCH_USER, FETCH_USER_SUCCESS, FETCH_USER_FAILURE,
  SHOW_POPUP, HIDE_POPUP,
  EDIT_PROFILE_POPUP, EDIT_PROFILE_POPUP_SUCCESS, EDIT_PROFILE_POPUP_FAILURE,
};
