export const SIGN_IN = 'User/SIGN_IN';
export const SIGN_IN_SUCCESS = 'User/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'User/SIGN_IN_FAILURE';

export const SIGN_UP = 'User/SIGN_UP';
export const SIGN_UP_SUCCESS = 'User/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'User/SIGN_UP_FAILURE';

export const FETCH_PROFILE = 'User/FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS= 'User/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'User/FETCH_PROFILE_FAILURE';

export const OPEN_REGISTRATION = 'User/OPEN_REGISTRATION';
export const OPEN_PROFILE = 'User/OPEN_PROFILE';
export const SHOW_MODAL = 'User/SHOW_MODAL';
export const HIDE_MODAL = 'User/HIDE_MODAL';

// noinspection JSUnusedGlobalSymbols
export default {
  SIGN_IN, SIGN_IN_FAILURE, SIGN_IN_SUCCESS,
  FETCH_PROFILE, FETCH_PROFILE_FAILURE, FETCH_PROFILE_SUCCESS,
  SIGN_UP, SIGN_UP_FAILURE, SIGN_UP_SUCCESS,
  OPEN_REGISTRATION, OPEN_PROFILE, SHOW_MODAL, HIDE_MODAL
};
